<div align="center">

**LAPORAN PRAKTIKUM**

**ALGORITMA DAN PEMOGRAMAN**

**“Pengenalan Boolean, String, Konstanta, Input, dan Tipe Data Numerik dalam Python”**

**Disusun Oleh :**

**Muhammad Hanif Fauzan**

**2611532021**

**Dosen Pengampu:**

**Dr. Ir WAHYUDI, ST., MT.**

**Asisten Praktikum:**

**Rifky Yuliandra**

<br>

 <img src="images/logo_unand.png" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji syukur kehadirat Allah subhanahu wata'ala atas segala rahmat dan karunia-Nya sehingga laporan praktikum pertemuan kedua dapat diselesaikan dengan baik.

Laporan ini disusun untuk memenuhi tugas praktikum serta memperdalam pemahaman mengenai Boolean, String, Konstanta, Input, serta tipe data Numerik yang meliputi int, float, dan complex. Materi tersebut diterapkan melalui beberapa program sederhana dalam Python.

Penulis menyadari bahwa laporan ini masih memiliki kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan demi perbaikan laporan di masa mendatang. Semoga laporan ini dapat memberikan manfaat bagi pembaca.

Padang, 2026

Muhammad Hanif Fauzan

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang
Pemahaman terhadap tipe data dan konsep dasar pemrograman diperlukan dalam proses pembuatan suatu program. Penggunaan tipe data yang sesuai dapat membantu dalam mengolah dan menyajikan data berdasarkan kebutuhan program.

Pada praktikum pertemuan kedua, dipelajari beberapa konsep dasar Python, yaitu Boolean, String, Konstanta, Input, serta tipe data Numerik yang meliputi int, float, dan complex. Konsep-konsep tersebut diterapkan dalam beberapa program sederhana untuk memahami penggunaannya dalam pemrograman.

## 1.2 Tujuan

1. Memahami penggunaan tipe data **Boolean, String, dan Numerik** dalam Python.
2. Memahami penggunaan **konstanta** dalam pembuatan program.
3. Memahami penggunaan fungsi `input()` untuk menerima masukan dari pengguna.
4. Menerapkan konsep-konsep tersebut dalam pembuatan program sederhana.

## 1.3 Manfaat

1. Meningkatkan pemahaman mengenai penggunaan berbagai tipe data dalam Python.
2. Menambah kemampuan dalam membuat program yang menerima dan mengolah masukan pengguna.
3. Membantu memahami penerapan konsep dasar Python melalui program sederhana.

---
# BAB II
# PEMBAHASAN

## 2.1 Dasar Teori

## 2.1 Dasar Teori

1. **Boolean** merupakan tipe data yang memiliki dua nilai, yaitu `True` dan `False`. Boolean dapat digunakan untuk menentukan hasil dari suatu kondisi dan dapat dikombinasikan menggunakan operator logika seperti `and` [1].

2. **String** merupakan tipe data yang digunakan untuk menyimpan data berupa teks. String dapat ditulis menggunakan tanda kutip tunggal (`'`) maupun tanda kutip ganda (`"`). Python juga mendukung *multiline string* yang dapat digunakan untuk menyimpan teks dalam beberapa baris [1].

3. **Konstanta** merupakan nilai yang dimaksudkan untuk tetap digunakan selama program berjalan. Dalam Python, konstanta dapat ditandai menggunakan `Final` dari modul `typing` untuk menunjukkan bahwa suatu variabel dimaksudkan untuk tidak diubah. Pada praktikum ini, konstanta `PI` digunakan dalam perhitungan luas lingkaran [3].

4. **Input** digunakan untuk menerima masukan dari pengguna saat program dijalankan. Fungsi `input()` menghasilkan data dalam bentuk string, sehingga data tersebut perlu dikonversi ke tipe data yang sesuai apabila akan digunakan dalam operasi numerik [2].

5. **Tipe data Numerik** digunakan untuk merepresentasikan nilai angka dalam Python. Tipe data numerik yang digunakan pada praktikum ini meliputi `int` untuk bilangan bulat, `float` untuk bilangan desimal, dan `complex` untuk bilangan kompleks [1].

## 2.2 Kode Program

### 2.2.1 Program boolean_2611532021

In [2]:
# program praktikum minggu 2. 9/10/26.
# program ini mengunakan tipe data boolean untuk menentukan status kelulusan mahasiswa.

# deklarasi variabel dengan tipe data boolean
is_lulus_2021 = True
is_cumlaude_2021 = True

# menggunakan boolean
nilai_2021 = 85
batas_lulus_2021 = 75

# menentukan nilai boolean dari kondisi
status_kelulusan_2021 = nilai_2021 >= batas_lulus_2021 # Hasilnya akan True

# mencetak nilai boolean
print("=== Check Kelulusan ===")
print("Nilai:", nilai_2021)
print("Apakah lulus?:", status_kelulusan_2021)
if is_lulus_2021 and is_cumlaude_2021:
    print("Selamat, Anda lulus dengan peringkat cumlaude!")




=== Check Kelulusan ===
Nilai: 85
Apakah lulus?: True
Selamat, Anda lulus dengan peringkat cumlaude!


**Penjelasan :**

1. Bagian pertama kode ini berfungsi untuk mendeklarasikan variabel `is_lulus_2021` dan `is_cumlaude_2021` dengan nilai Boolean `True`.

2. Bagian kedua berfungsi untuk menyimpan nilai mahasiswa dan batas nilai kelulusan ke dalam variabel `nilai_2021` dan `batas_lulus_2021`.

3. Bagian ketiga berfungsi untuk menentukan status kelulusan dengan membandingkan `nilai_2021` dengan `batas_lulus_2021`. Hasil perbandingan tersebut berupa nilai Boolean.

4. Bagian keempat berfungsi untuk menampilkan judul **"Check Kelulusan"** pada layar.

5. Bagian kelima berfungsi untuk menampilkan nilai yang tersimpan dalam variabel `nilai_2021`.

6. Bagian keenam berfungsi untuk menampilkan status kelulusan yang tersimpan dalam variabel `status_kelulusan_2021`.

7. Bagian ketujuh berfungsi untuk memeriksa apakah `is_lulus_2021` dan `is_cumlaude_2021` keduanya bernilai `True` menggunakan operator `and`.

8. Bagian kedelapan berfungsi untuk menampilkan pesan bahwa mahasiswa lulus dengan peringkat cumlaude apabila kondisi pada `if` terpenuhi.

### 2.2.2 Program input_2611532021

In [10]:
# program praktikum minggu 2. 9/10/26. 
# program ini mengunakan fungsi input() untuk meminta pengguna
# memasukkan nilai panjang dan lebar persegi panjang.
# nilai yang dimasukkan akan dikonversi menjadi tipe data integer

panjang_2021 = input("Masukkan nilai panjang: ")
lebar_2021 = input("Masukkan nilai lebar: ")
luas_2021 = int(panjang_2021) * int(lebar_2021)

print("Luas persegi panjang adalah: ", luas_2021)    

Luas persegi panjang adalah:  25


**Penjelasan :**

1. Bagian pertama kode ini berfungsi untuk meminta pengguna memasukkan nilai panjang persegi panjang menggunakan fungsi `input()`. Nilai yang dimasukkan disimpan dalam variabel `panjang_2021`.

2. Bagian kedua berfungsi untuk meminta pengguna memasukkan nilai lebar persegi panjang menggunakan fungsi `input()`. Nilai yang dimasukkan disimpan dalam variabel `lebar_2021`.

3. Bagian ketiga berfungsi untuk menghitung luas persegi panjang dengan mengalikan nilai panjang dan lebar. Fungsi `int()` digunakan untuk mengonversi nilai yang diperoleh dari `input()` menjadi tipe data integer.

4. Bagian keempat berfungsi untuk menampilkan hasil perhitungan luas persegi panjang pada layar.

### 2.2.3 Program konstanta_2611532021

In [11]:
# program praktikum minggu 2. 9/10/26.
# program ini menggunakan konstanta untuk menghitung luas lingkaran.

from typing import Final
PI: Final = 3.14
print("pi: %f" % (PI))
jari_2021 = float(input("Masukkan nilai jari-jari: "))
luas_2021 = PI * jari_2021 * jari_2021
print("Luas lingkaran dengan jari-jari %.2f adalah: %.2f" % (jari_2021, luas_2021))


pi: 3.140000
Luas lingkaran dengan jari-jari 5.00 adalah: 78.50


**Penjelasan :**

1. Bagian pertama berfungsi untuk mengimpor `Final` dari modul `typing` agar variabel dapat ditandai sebagai nilai yang dimaksudkan untuk tetap.

2. Bagian kedua berfungsi untuk mendeklarasikan `PI` sebagai konstanta dengan nilai `3.14`.

3. Bagian ketiga berfungsi untuk menampilkan nilai konstanta `PI` dengan format bilangan desimal.

4. Bagian keempat berfungsi untuk meminta pengguna memasukkan nilai jari-jari lingkaran. Fungsi `float()` digunakan untuk mengubah input menjadi tipe data desimal.

5. Bagian kelima berfungsi untuk menghitung luas lingkaran dengan menggunakan nilai `PI` dan jari-jari yang telah dimasukkan.

6. Bagian keenam berfungsi untuk menampilkan hasil perhitungan luas lingkaran dengan format dua angka di belakang koma.

### 2.2.4 Program numerik_2611532021

In [12]:
# program praktikum minggu 2. 9/10/26. 
# program ini mengunakan fungsi type() untuk menampilkan tipe data dari variabel yang dibuat.

# create a variable with numeric type value
a_2021 = 100
print("The type of variable having value", a_2021, " is ", type(a_2021))

# create a variable with float value.
b_2021 = 10.2345
print("The type of variable having value", b_2021, " is ", type(b_2021))

# create a variable with complex value.
c_2021 = 100 + 3j
print("The type of variable having value", c_2021, " is ", type(c_2021))

The type of variable having value 100  is  <class 'int'>
The type of variable having value 10.2345  is  <class 'float'>
The type of variable having value (100+3j)  is  <class 'complex'>


**Penjelasan :**

1. Bagian pertama berfungsi untuk membuat variabel `a_2021` dengan nilai `100`, kemudian menggunakan fungsi `type()` untuk menampilkan tipe data dari variabel tersebut.

2. Bagian kedua berfungsi untuk membuat variabel `b_2021` dengan nilai `10.2345`, kemudian menggunakan fungsi `type()` untuk menampilkan tipe data dari variabel tersebut.

3. Bagian ketiga berfungsi untuk membuat variabel `c_2021` dengan nilai kompleks `100 + 3j`, kemudian menggunakan fungsi `type()` untuk menampilkan tipe data dari variabel tersebut.

### 2.2.5 Program string_2611532021

In [13]:
# program praktikum minggu 2. 9/10/26. 
# program ini mengunakan fungsi input() untuk meminta pengguna
# memasukkan nilai panjang dan lebar persegi panjang.

# data variables
nama_2021 = "Muhammad Hanif Fauzan"
jenis_kelamin_2021 = 'L'
alamat_2021 = """
    Jl. KIS Mangusnsarkoro
    kec. Padang Timur
    Kota Padang
"""
agama_2021 = "Islam"

# print the data variables
print("Nama saya adalah: ", nama_2021)
print("Jenis kelamin saya adalah: ", jenis_kelamin_2021)
print("Alamat saya adalah: ", alamat_2021)
print("Agama saya adalah: ", agama_2021)
    


Nama saya adalah:  Muhammad Hanif Fauzan
Jenis kelamin saya adalah:  L
Alamat saya adalah:  
    Jl. KIS Mangusnsarkoro
    kec. Padang Timur
    Kota Padang

Agama saya adalah:  Islam


**Penjelasan :**

1. Bagian pertama berfungsi untuk membuat variabel `nama_2021`, `jenis_kelamin_2021`, `alamat_2021`, dan `agama_2021` yang menyimpan data dalam bentuk String.

2. Bagian kedua berfungsi untuk menyimpan alamat dalam bentuk *multiline string*, yaitu String yang ditulis dalam beberapa baris menggunakan tiga tanda kutip (`"""`).

3. Bagian ketiga berfungsi untuk menampilkan data yang telah disimpan dalam variabel `nama_2021`, `jenis_kelamin_2021`, `alamat_2021`, dan `agama_2021` menggunakan fungsi `print()`.

---
## Tugas Praktikum

**Soal :**

<div align="center">
<img src="images/soal_tugas.png" width="500"><br>
<em>Gambar 2.2 : Soal Tugas Praktikum</em>
</div>

**Kode Jawaban :**

a. Kode Program "NamaKelas_NIM"

In [5]:
# Kode jawaban tugas bagian a

b. Kode Program Driver "NamaDriver_NIM"

In [6]:
# Kode jawaban tugas bagian b (driver)

**Output :**

<div align="center">
<img src="images/output_tugas.png" width="400"><br>
<em>Gambar 2.3 : Output Tugas Praktikum</em>
</div>

**Penjelasan :** Program tugas ini ...

---
# BAB III
# KESIMPULAN

Berdasarkan praktikum yang telah dilakukan, dapat disimpulkan bahwa konsep dasar Python meliputi penggunaan tipe data Boolean, String, dan Numerik, serta penggunaan konstanta dan fungsi input(). Masing-masing konsep memiliki penggunaan yang berbeda dalam pengolahan data pada program.

Melalui praktikum ini, konsep-konsep tersebut dapat diterapkan dalam beberapa program sederhana, seperti menentukan status kelulusan, menampilkan data berbentuk teks, menghitung luas lingkaran dan persegi panjang, serta mengetahui tipe data numerik menggunakan fungsi type(). Dengan demikian, praktikum ini membantu memahami penerapan berbagai konsep dasar Python dalam pembuatan program.

---
## DAFTAR PUSTAKA

[1] Python Software Foundation. *The Python Tutorial: An Informal Introduction to Python*. Python Documentation.

[2] Python Software Foundation. *Input and Output*. Python Documentation.

[3] Python Software Foundation. *typing — Support for Type Hints*. Python Documentation.